apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:  
        - name: nginx
          image: us-central1-docker.pkg.dev/tp-gke-458909/somme-python-repo/nginx-demo:234f49d40a04525167597419adb51a590098125a
          ports:
            - containerPort: 80
